---@class RestockerAddon
---@field addon table Main frame of the addon
---@field EventFrame table Hidden frame for addon events
---@field loaded boolean
---@field itemWaitTable table<string, any>
---@field bankIsOpen boolean
---@field merchantIsOpen boolean
---@field TBC boolean Whether we are running TBC or Classic Era
